### ISSUE TITLE
Enforce IPForward=kernel easily

### ISSUE THREAD

**Issue by katanacrimson** [gh2o/digitalocean-debian-to-arch#25]
As on tin.  Trying to set IPForward=kernel (because systemd-networkd decided to be idiots and smother the fucking sysctl setting we already have) is a bit ridiculous.  Maybe check to see if sysctl has it set already and add the line, or just add IPForward=kernel outright?

**Comment by gh2o** [comment]
Thank you for your suggestion. As much as I also disagree with the choices made by the systemd team, I believe that it is outside the scope of this project to be modifying the defaults of the base install; the script should only do the minimum necessary to bootstrap the droplet and maintain its consistency through backups and restores.

**Comment by katanacrimson** [comment]
Then it should be either better documented or more discoverable tbh - it's some serious voodoo to have the ethernet configuration file for networkd just magically appear in `/run/`.

**Comment by robjens** [comment]
@damianb Thank you... I've been looking for the location of the network configuration for some time now, that little bugger wasn't at all where I'd expect it. I `+1` the call for a bit more outlining some of the particulars, especially in relation to digital ocean hosts I guess. Network is quite the biggie imho since about well almost any time one will have trouble getting actually in (ssh via vterm) a droplet, it will 9/10 times be the public network connection. Although we've been having a few issues with `eth1` as well. But this'll give me enough to work with for now. Btw, is the `eth0` name required? Or can it be e.g. `net0` and can `netctl` or such be used?

**Comment by vodik** [comment]
There is a template system for working around this. I created this file: `etc/systemd/network/template/dosync-eth0.network.tail` with the following line:

```
IPForward=ipv4
```

This causes `dosync-eth0.network` to look like this:

```
[Match]
Name=eth0
[Network]
Address=...
Gateway=...
IPForward=ipv4
```

And does the necessary trick. The template system is something unique to dosync and not a systemd-networkd feature. It be cool if networkd supported something like a `do-sync-eth0.d` style mixin like systemd does.

**Comment by vodik** [comment]
@damianb it ends up in /run because its generated per-boot and that's the appropriate place for these things to go, at least according to systemd. Order of folder precedence is defined as:
1. `/etc/systemd` (user provided)
2. `/run/systemd` (dynamically generated)
3. `/usr/lib/systemd` (distro provided)

So if you want, you can always write your own `dosync-eth0.network` file, but be wary you will have problems if you ever get renumbed.

**Comment by vodik** [comment]
@gh2o +1 on being out of scope.
