### ISSUE TITLE
Incompatible with snapshots?

### ISSUE THREAD

**Issue by jeaye** [gh2o/digitalocean-debian-to-arch#7]
I initially setup my system with this approach about 20 days ago and it's been working wonderfully. After creating some snapshots, I've found that I'm unable to boot a new droplet. That is, I can flawlessly take down my initial droplet and spin it back up, but I'm unable to spin up any new droplets using a snapshot of this system.

I've spent a couple of days going over this with the DigitalOcean support team and they've found nothing wrong on their end so I'm lead to believe it's some bad state from this transmutation. Since my evidence for this is inconclusive, I'd really appreciate it if anyone else would try the same thing. Snap shot your "Arch" system and try to spin up a droplet based on the snapshot; if it boots and you can log into it, you get further than me.

Otherwise, having written this system, perhaps you have some more troubleshooting suggestions. I've run fsck on the droplet (from a recovery kernel) with no reported errors and nothing in lost+found.

**Comment by gh2o** [comment]
That is odd indeed. I'm looking into it.

**Comment by iPerky** [comment]
Same issue.
System working perfectly but cannot create droplets with Snapshots or Backup images.

```
uname -a
Linux bit 3.14.27-1-lts #1 SMP Wed Dec 17 19:52:05 CET 2014 i686 GNU/Linux
```

**Comment by gh2o** [comment]
The issue seems to be twofold:

1. DigitalOcean seems to fail to restore snapshots if `/etc/network/interfaces` does not exist, since this is the file where networking settings for the new droplet is written.
2. The interfaces file is only parsed once at migration and never afterwards. This should be fixed in 1338f4dc75f6ac961853495ddb870c9872ebdcca, which installs a compatability package to parse the interfaces file at every startup.

**Comment by gh2o** [comment]
To get snapshots working again, do the following on a droplet that has already been migrated.

1. Get a working interfaces file for your droplet.
  * If you have not deleted `/oldroot` yet, you can simply copy the interfaces file over:
  ```
  mkdir -p /etc/network
  cp /oldroot/etc/network/interfaces /etc/network/interfaces
  ```
  * If `/oldroot` has been long deleted, you can write a new one into `/etc/network/interfaces`.
  ```
### Public IPv6
iface eth0 inet6 static
        address <IPv6 address>
        netmask 64
        gateway <IPv6 gateway>
        dns-nameservers 2001:4860:4860::8844 2001:4860:4860::8888 8.8.8.8
#### Public IPv4
iface eth0 inet static
        address <IPv4 address>
        netmask <IPv4 netmask>
        gateway <IPv4 gateway>
#### Private IPv4
iface eth1 inet static
        address <IPv4 address>
        netmask <IPv4 netmask>
   ```
2. Install the compatability package.
```wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/master/install.sh && bash install.sh```
3. Delete the old network configuration files.
```
rm -f /etc/systemd/network/internet.network
rm -f /etc/systemd/network/private.network
```

Reboot, and the droplet should now be snapshottable.

**Comment by gh2o** [comment]
Actually there appears to still be a problem... I'm not able to restore snapshots at all; it gives me an error saying "Action Did Not Complete" in the droplet history...

**Comment by gh2o** [comment]
Never mind, that was just an oddity with my droplet. Apparently if `/root/.ssh/authorized_keys` is a symlink, droplet restore will fail because they can't write the public keys specified at droplet creation. I fixed that and all is good.

**Comment by jeaye** [comment]
I was able to get this working by building my own `/etc/network/interfaces` as well. Thanks for documenting this.

**Comment by iPerky** [comment]
Snapshot now works with a fresh install but had problems with the root password when creating a new droplet from an archlinux snapshot.
I could not ```su``` from a wheel user because the password was not recognised.

My solution was to set-up sudo before taking a snapshot, then ```sudo su``` to reset ```passwd``` in the new droplet.

Will try Backup images next.

**Comment by gh2o** [comment]
The password is emailed to you upon droplet creation, or deleted if the droplet was created with an SSH key. It's currently rather difficult to preserve the password and keys across backups and restores because DigitalOcean directly overwrites `/etc/shadow` and `/root/.ssh/authorized_keys` upon restoring a droplet from a snapshot.

**Comment by iPerky** [comment]
Thanks for the password and keys info. Good to know.

Snapshots and Back-up tested and working again for archlinux

**Comment by andxet** [comment]
I deleted the oldroot and now I have to recreate the /etc/network/interfaces, but I don't understand how to do it. I know the ipv4, but netmask and gateway? I should add the loopback interface?

**Comment by chrisbgp** [comment]
Can someone update this for the debian8 script? I did generate /etc/network/interfaces but it still does not work with snapshots...

Therre is no /oldroot in debian8 either
